@startuml
'https://plantuml.com/class-diagram

title Class Diagram
caption \nKlassediagrammet viser objekter, interfacer, enums etc.


abstract class AbstractList
abstract AbstractCollection {
    String title
    Integer length
    getLength()
    getTitle()
}
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
    Object[] elementData
    size()
    insert()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml